### ISSUE TITLE
Error on HomeScreen

### ISSUE THREAD

**Issue by cristianfb1989** [piedcipher/WallE#2]
Hello, how are you?

I tried to run your project, and I got this error. What can I do?
![2019-11-03_21-02-57](https://user-images.githubusercontent.com/16965222/68094277-72afc600-fe7d-11e9-8911-e8dbe4b05057.png)

Thx

**Comment by piedcipher** [comment]
Did you follow the steps mentioned in [Setup](https://github.com/piedcipher/WallE#setup)?
<img src="https://i.imgur.com/YgkZyat.png" />

**Comment by cristianfb1989** [comment]
oh, f#ck! Thank you for the info! Sorry!

**Comment by piedcipher** [comment]
It's ok. Happens with best of us. :)

**Comment by piedcipher** [comment]
Is it resolved?

**Comment by cristianfb1989** [comment]
@piedcipher Yes, thx you!!
